services:
  web:
    build: .
    depends_on:
      - db
      - rabbit
    restart: "no"
    entrypoint: bash /opt/rnatango/docker-entrypoint.sh
    env_file:
      - ./.env
    ports:
      - 8080:8080
    networks:
      - web_network
      - db_network
      - rabbit_network
    volumes:
      - .:/opt/rnatango
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   #restart: always
  #   ports:
  #    - "5050:5050"
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@rnapolis.pl
  #     PGADMIN_DEFAULT_PASSWORD: zaq1@WSXcde3
  #     PGADMIN_LISTEN_PORT: 5050
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   networks:
  #     - db_network
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:8000
      - 443:443
    depends_on:
      - web
    volumes:
      - ./ssl:/etc/letsencrypt/
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./logs/nginx:/logs
      - ./frontend:/usr/share/nginx/html
    networks:
      - web_network
  maxit:
    image: tzok/maxit:server
    restart: always
    networks:
      - web_network
  rabbit:
    image: rabbitmq:3.11-alpine
    restart: always
    env_file:
      - ./.env
    networks:
      - db_network
      - rabbit_network
  db:
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - db_network
volumes:
  workdir:
  pgdata:
  pgadmin-data:
networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
  rabbit_network:
    driver: bridge
