services:
  web:
    build: .
    depends_on:
      - db
      - rabbit
    restart: always
    env_file:
      - ./.env
    volumes:
      - frontend:/shared/frontend

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - 80:8000
      - 443:443
    depends_on:
      - web
    volumes:
      - ./ssl:/etc/letsencrypt/
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./logs/nginx:/logs
      - frontend:/usr/share/nginx/html

  maxit:
    image: tzok/maxit:server
    restart: always

  rabbit:
    image: rabbitmq:3.11-alpine
    restart: always
    env_file:
      - ./.env

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  pgdata:
  frontend:
